version: "3.8"

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    ports:
      - "9090:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
