{
 "title": "My Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu_seconds_total{job=\"Jupiter-Arco\",instance=\"localhost:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\", job=\"Jupiter-Arco\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"Jupiter-Arco\"} - node_memory_Cached_bytes{instance=\"localhost:9100\",job=\"Jupiter-Arco\"} - node_memory_Buffers_bytes{instance=\"localhost:9100\",job=\"Jupiter-Arco\"} ",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\",job=\"Jupiter-Arco\"} ",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\",job=\"Jupiter-Arco\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"localhost:9100\",job=\"Jupiter-Arco\"} ",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"Jupiter-Arco\", instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}}receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"Jupiter-Arco\", instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}}transmit"
    }
   ]
  }
 ]
}