#!/usr/bin/env sh 
#path to this file : /usr/bin/nnnopen
if [[ ! -f "$1" ]];then
	exit
fi

mime=$(file -b --mime-type "$1")
echo $mime

# image/*
if [[ "${mime%/*}" = "image" ]];then
	sxiv -ab "$1"
# video/*
elif [[ "${mime%/*}" = "video" || "${mime%/*}" = "audio" ]];then
    mpv --player-operation-mode=pseudo-gui -- "$@"
	# mpv "$1"
	# swallow mpv "$1"

# vim
elif [[ "${mime%/*}" = "text" || "$mime" = "application/json" || "$mime" = "application/x-setupscript" ]]; then
    kitty -e nvim "$1"

# ebooks 
elif [[ "$mime" = "application/epub+zip" || "$mime" = "application/pdf" ]];then
	zathura "$1"

# rnote
elif [[ "$mime" = "application/gzip" ]];then
	rnote "$1"

# libreoffice files
elif [[ "$mime" = "application/vnd.oasis.opendocument.text" || \
        "$mime" = "application/vnd.openxmlformats-officedocument.wordprocessingml.document" || \
        "$mime" = "application/vnd.openxmlformats-officedocument.presentationml.presentation" ]]; then
    libreoffice "$1"

fi
