#!/usr/bin/env sh 
#path to this file : /usr/bin/nnnopen
if [[ ! -f "$1" ]];then
	exit
fi

mime=$(file -b --mime-type "$1")
echo $mime
# m3u files report as text/plain for some reason
if [[ "${1#*.}" = "m3u" ]];then
	swallow mpv "$1"

# text/*
#elif [[ "${mime%/*}" = "text" ]];then
#	nnnedit "$1"

# image/*
elif [[ "${mime%/*}" = "image" ]];then
	sxiv -ab "$1"
# video/*
elif [[ "${mime%/*}" = "video" || "${mime%/*}" = "audio" ]];then
	swallow mpv "$1"
# ebooks 
elif [[ "$mime" = "application/epub+zip" ]];then
	zathura "$1"
# pdfs 
elif [[ "$mime" = "application/pdf" ]];then
	zathura "$1"
# exe 
elif [[ "$mime" = "application/x-dosexec" ]];then
	wine "$1"
elif [[ "$mime" = "application/vnd.oasis.opendocument.text" ]];then
	libreoffice "$1"
elif [[ "$mime" = "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ]];then
	libreoffice "$1"
elif [[ "$mime" = "application/vnd.openxmlformats-officedocument.presentationml.presentation" ]];then
	libreoffice "$1"
# rnote
elif [[ "$mime" = "application/gzip" ]];then
	rnote "$1"
# html 
elif [[ "$mime" = "text/html" ]];then
	firefox "$1"
# plain txt
elif [[ "$mime" = "text/plain" ]];then
	kitty -e lvim "$1"
# shellscript 
elif [[ "$mime" = "text/x-shellscript" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/x-perl" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "application/json" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/troff" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "application/x-setupscript" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/x-c++" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/x-script.python" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/csv" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/x-java" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/xml" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/x-ruby" ]];then
	kitty -e lvim "$1"
elif [[ "$mime" = "text/x-file" ]];then
	kitty -e lvim "$1"
# word docs 
elif [[ "$mime" = "application/vnd.oasis.opendocument.text" ]];then
	libreoffice "$1"
elif [[ "$mime" = "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ]];then
	libreoffice "$1"

fi
