#!/bin/bash
#
# nnn plugins => imgview ,, edit below line: 
# sxiv) listimages | xargs -0 swallow sxiv -a "${count:--t}" -- ;;
#
while read file
do
        case "$1" in
        "c")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ~/scripts/dires | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/scripts}/dires | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
		[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
  "x")
    xclip -selection clipboard -target image/png "$file" &&
    notify-send "$file has been copied to clipboard." && exit 0 
    ;;
  "w") 
      xwallpaper --stretch "$file" &&
      cp "$file" ~/.cache/wall/wallpaper.jpg 
      notify-send -t 1500 -i ~/logo/wall.jpg "$file has been set as your wallpaper." && exit 0
    ;;

  "g")
     pacman -Qq "gimp" >/dev/null 2>&1 && gimp "$file" ||
     notify-send "ERROR" "\nGimp is not installed! Install gimp if you want to use this function in sxiv:\n\nsudo pacman -S gimp" && 
     exit 1;
     ;;
        esac
done
